# You can use a Docker image from Docker Hub or your own container registry for your build environment.

image: wooyek/geodjango

pipelines:
  default:
    - step:
        script:

          # Pipelines overrides default docker entry point, we need to run it manually
          - docker-entrypoint.sh

          # Print debug information
          - pwd
          - ls
          - pip --version
          - tox --version

          # Test the application
          - mkdir -p .tmp/coverage
          - tox
