# Generated by Django 4.0.3 on 2022-08-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('binary', models.BinaryField()),
                ('boolean', models.BooleanField()),
                ('char', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('decimal', models.DecimalField(decimal_places=8, max_digits=10)),
                ('duration', models.DurationField()),
                ('float', models.FloatField()),
                ('ip', models.GenericIPAddressField()),
                ('integer', models.IntegerField()),
                ('small_int', models.SmallIntegerField()),
                ('json', models.JSONField()),
                ('positive_big_int', models.PositiveBigIntegerField()),
                ('positive_int', models.PositiveIntegerField()),
                ('positive_small_int', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=20)),
                ('text', models.TextField()),
                ('time', models.TimeField(auto_now=True)),
                ('url', models.URLField()),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelARel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('foreign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreigns', to='test_app_a.modela')),
                ('many', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='many', to='test_app_a.modela')),
                ('one', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='one', to='test_app_a.modela')),
            ],
        ),
    ]
